/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {},
    colors: {
      gray: {
        900: "#121212",
        800: "#2b2b2b",
        700: "#3a3a3a",
        600: "#4f4f4f",
        500: "#6b6b6b",
        400: "#8f8f8f",
        300: "#bfbfbf",
        200: "#e2e2e2",
        100: "#f5f5f5",
        50: "#f9f9f9",
      },
      blue: {
        900: "#0d6efd",
        800: "#0dcaf0",
        700: "#0dcaf0",
        600: "#0dcaf0",
        500: "#0dcaf0",
        400: "#0dcaf0",
        300: "#0dcaf0",
        200: "#0dcaf0",
        100: "#0dcaf0",
        50: "#0dcaf0",
      },
    },
  },
  plugins: [require("daisyui"), require("@tailwindcss/line-clamp")],

  daisyui: {
    styled: true,
    themes: true,
    base: true,
    utils: true,
    logs: true,
    rtl: false,
    prefix: "",
    darkTheme: "dark",
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
    ],
  },
};
